// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type RedirectRedirectTarget struct {
	_    structs.HostLayout
	Ip   uint32
	Port uint32
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	RedirectMapRedirectMap      = "redirect_map"
	RedirectProgRedirectConnect = "redirect_connect"
)

// LoadRedirect returns the embedded CollectionSpec for Redirect.
func LoadRedirect() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_RedirectBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Redirect: %w", err)
	}

	return spec, err
}

// LoadRedirectObjects loads Redirect and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*RedirectObjects
//	*RedirectPrograms
//	*RedirectMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadRedirectObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadRedirect()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// RedirectSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type RedirectSpecs struct {
	RedirectProgramSpecs
	RedirectMapSpecs
	RedirectVariableSpecs
}

// RedirectProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type RedirectProgramSpecs struct {
	RedirectConnect *ebpf.ProgramSpec `ebpf:"redirect_connect"`
}

// RedirectMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type RedirectMapSpecs struct {
	RedirectMap *ebpf.MapSpec `ebpf:"redirect_map"`
}

// RedirectVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type RedirectVariableSpecs struct {
}

// RedirectObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadRedirectObjects or ebpf.CollectionSpec.LoadAndAssign.
type RedirectObjects struct {
	RedirectPrograms
	RedirectMaps
	RedirectVariables
}

func (o *RedirectObjects) Close() error {
	return _RedirectClose(
		&o.RedirectPrograms,
		&o.RedirectMaps,
	)
}

// RedirectMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadRedirectObjects or ebpf.CollectionSpec.LoadAndAssign.
type RedirectMaps struct {
	RedirectMap *ebpf.Map `ebpf:"redirect_map"`
}

func (m *RedirectMaps) Close() error {
	return _RedirectClose(
		m.RedirectMap,
	)
}

// RedirectVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadRedirectObjects or ebpf.CollectionSpec.LoadAndAssign.
type RedirectVariables struct {
}

// RedirectPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadRedirectObjects or ebpf.CollectionSpec.LoadAndAssign.
type RedirectPrograms struct {
	RedirectConnect *ebpf.Program `ebpf:"redirect_connect"`
}

func (p *RedirectPrograms) Close() error {
	return _RedirectClose(
		p.RedirectConnect,
	)
}

func _RedirectClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed redirect_bpfeb.o
var _RedirectBytes []byte
